[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/faq"
  to = "/faq.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200

[[redirects]]
  from = "/blog-cost-of-staying"
  to = "/blog-cost-of-staying.html"
  status = 200

[[redirects]]
  from = "/blog-leave-adp-totalsource"
  to = "/blog-leave-adp-totalsource.html"
  status = 200

[[redirects]]
  from = "/blog-peo-exit-checklist"
  to = "/blog-peo-exit-checklist.html"
  status = 200

[[redirects]]
  from = "/blog-workers-comp-epli"
  to = "/blog-workers-comp-epli.html"
  status = 200

[[redirects]]
  from = "/blog-401k-transition"
  to = "/blog-401k-transition.html"
  status = 200

[[redirects]]
  from = "/blog-peo-tax-credits"
  to = "/blog-peo-tax-credits.html"
  status = 200

[[redirects]]
  from = "/blog-funding-options"
  to = "/blog-funding-options.html"
  status = 200
[[redirects]]
  from = "/blog-peo-exit-case-study"
  to = "/blog-peo-exit-case-study.html"
  status = 200
[[redirects]]
  from = "/blog-insperity-problems"
  to = "/blog-insperity-problems.html"
  status = 200
[[redirects]]
  from = "/blog/peo-invoice-audit"
  to = "/blog/peo-invoice-audit.html"
  status = 200
  force = true
